apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: metrics-app-dev
  namespace: acm-poc-devteam1-gitops
  labels:
    app: acm-poc-devteam1-gitops-app
spec:
  channel: acm-poc-devteam1-gitops/acm-poc-devteam1-gitops-channel
  name: metrics-app
  packageFilter:
    version: "0.1.0"
  placement:
    placementRef:
      kind: PlacementRule
      name: devcluster
  packageOverrides:
  - packageName: metrics-app
    packageOverrides:
      - path: spec
        version:
          barista:  5.0.0-SNAPSHOT
          counter:  5.0.1-SNAPSHOT
          customermocker:  5.0.1-SNAPSHOT
          inventory: 5.0.0-SNAPSHOT
          kitchen:  5.0.0-SNAPSHOT
          web:  5.0.3-SNAPSHOT
