apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix:  staging-
resources:
  - ../../base
replicas:
- name: staging-sampleapp-metrics-app
  count: 3
- name: staging-sampleapp-cloudprober
  count: 3