apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix:  production-
resources:
  - ../../base
replicas:
- name: production-sampleapp-metrics-app
  count: 3
- name: production-sampleapp-cloudprober
  count: 3